### ISSUE TITLE
CRG: use LiteX's S7MMCM ?

### ISSUE THREAD

**Issue by enjoy-digital** [betrusted-io/betrusted-soc#11]
LiteX provides a S7MMCM that could simplify the CRG and would compute automatically the MMCME2_ADV's parameters from specified input/outputs. It also has DRP support.

An example of use: https://github.com/enjoy-digital/litex/blob/master/litex/boards/targets/arty.py#L35-L42

Is it something you would like to use? I'm happy to create a pull request if so.

**Comment by bunnie** [comment]
Yes, I'd be curious to try it. The divider ratios are a little tricky to get right, some are better for jitter performance etc. If I find the dividers aren't being calculated optimally, I'll send a PR back to you with some suggestions?

**Comment by enjoy-digital** [comment]
OK, i'll prepare that. Any feedback/improvement on S7PLL/S7MMCM will be welcome.

**Comment by bunnie** [comment]
I think I understand what you're doing here and it looks pretty good. I had one minor suggestion to allow for a "precise" solution to the clocks, as so far the clocks were planned to divide evenly throughout the system. 

With the default margin=0.01, the solution converges on a sub-optimal situation, but I can't specify margin=0. I can do margin=0.001 and it gets the right solution, but because the clocks were planned by design to divide perfectly it'd be nice to have the option for that to come out, and when I mess up, for it to throw an error.
